// swift-tools-version: 6.0
// Swift Package manifest for EmberScope ONLY. It lets any app add this repository as a package
// dependency (File ▸ Add Package Dependencies ▸ this repo's URL) and `import EmberScope`, netfox-style.
// The Ember app itself is NOT a package: it is generated by Tuist from Project.swift, and Tuist's
// dependency manifest lives in Tuist/Package.swift — this file is ignored by `tuist generate`.
import PackageDescription

let package = Package(
    name: "EmberScope",
    platforms: [.iOS("26.0"), .macOS("26.0")],
    products: [.library(name: "EmberScope", targets: ["EmberScope"])],
    targets: [
        .target(name: "EmberScope", path: "Targets/EmberScope/Sources/EmberScope"),
        .testTarget(name: "EmberScopeTests", dependencies: ["EmberScope"],
                    path: "Targets/EmberScope/Tests/EmberScopeTests"),
    ]
)
